#!/bin/bash

# XY (plan)
openscad --render --imgsize=1000,1000 --projection=o --camera=0,0,0,180,0,0,5000 -o examples/eccentric-strap-xy.png examples/eccentric-strap.scad 2>&1| grep DATUM > examples/eccentric_strap.data

# XZ (elevation)
openscad --render --imgsize=1000,1000 --projection=o --camera=0,0,0,90,0,0,5000 -o examples//eccentric-strap-xz.png examples/eccentric-strap.scad 2>&1| grep DATUM > examples/eccentric_strap.data

# YZ (side elevation)
openscad --render --imgsize=1000,1000 --projection=o --camera=0,0,0,90,0,90,5000 -o examples//eccentric-strap-yz.png examples/eccentric-strap.scad 2>&1| grep DATUM > examples/eccentric_strap.data

# XZ (plan) dimensions
#draw_examples/.tcl examples//eccentric_strap.data examples//eccentric-strap-xz.png y